# Generated by Django 5.2 on 2025-04-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfields',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
